--주소록 테이블 생성
--id varchar(100),name varchar(100)
CREATE TABLE ADDR(
	ID VARCHAR(100),
	NAME VARCHAR(100)
);
--주소록에 컬럼추가 birth date
ALTER TABLE ADDR ADD(BIRTH DATE);

SELECT *FROM ADDR2;

--주소록에 COMMMENTS 컬럼 추가 VARCHAR(200) 기본값 'NO COMMENT'
ALTER TABLE ADDR ADD(COMMENTS VARCHAR(200) DEFAULT 'NO COMMENT');

INSERT INTO ADDR(ID) VALUES('ID1');

--주소록에 COMMENTS 컬럼 삭제
ALTER TABLE ADDR DROP (COMMENTS);

--주소록 ID 컬럼의 크기를 1 BYTE로 변경
ALTER TABLE ADDR MODIFY ID VARCHAR(1);--오류 메시지가 나오는데 크기가 작게 만들수 없다함

ALTER TABLE ADDR MODIFY ID VARCHAR(10);--이거는 가능

--ADDR 테이블 이름을 ADDR2로 변경
RENAME ADDR TO ADDR2;

--ADDR2 테이블에다가 '주소록'이라는 COMMENT 추가
COMMENT ON TABLE ADDR2 IS '주소록';--주석 추가

--ADDR2의 NAME 컬럼에 '이름'이라는 COMMENT 추가
COMMENT ON COLUMN ADDR2.NAME IS '이름';

--강좌 테이블 생성(SUBJECT)
--SUBNO번호
--SUBNAME 이름
--TERM학기(1,2)
--TYPE 필수 여부  CHAR(1)
DROP TABLE SUBJECT;

CREATE TABLE SUBJECT(
	SUBNO NUMBER CONSTRAINT SUBJECT_PK PRIMARY KEY,--CONSTRAINT 강좌 테이블 생성하고 이름주기
	SUBNAME VARCHAR(200) CONSTRAINT SUBNAME_NN NOT NULL,
	TERM CHAR(1) CONSTRAINT TERM_CK CHECK (TERM IN('1,2')),--차 타입이라 문자열로
	TYPE CHAR(1)
);

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY(STUDNO);

 SELECT *FROM STUDENT s ;

CREATE TABLE SUGANG(
	STUDNO CONSTRAINT SUGANG_STUDNO_FK REFERENCES STUDENT,
	SUBNO NUMBER,
	REGDATE DATE,
	RESULT NUMBER(3),
	CONSTRAINT SUGANG_SUBNO_FK FOREIGN KEY(SUBNO) REFERENCES SUBJECT(SUBNO),
	CONSTRAINT SUGANG_PK PRIMARY KEY(STUDNO,SUBNO)
);

DROP TABLE SUGANG;

-- 학과 테이블의 제약조건 넣기
--PK:DETNO, NN:DNAME, <> DEPTNO: FK
ALTER TABLE DEPARTMENT MODIFY (DEPTNO CONSTRAINT DEPARTMENT_PK PRIMARY KEY);
ALTER TABLE DEPARTMENT MODIFY (DNAME NOT NULL);
ALTER TABLE DEPARTMENT MODIFY (COLLEGE REFERENCES DEPARTMENT(DEPTNO));


--교수 테이블에 제약조건 넣기
--pk ,이름nn,아이디unique ,FK DNPTNO
ALTER TABLE PROFESSOR ADD CONSTRAINT PROFESSOR_PK PRIMARY KEY(PROFNO);
ALTER TABLE PROFESSOR  MODIFY (NAME NOT NULL);
ALTER TABLE PROFESSOR ADD CONSTRAINT PROF_USERID_UK UNIQUE(USERID);
ALTER TABLE PROFESSOR ADD FOREIGN KEY(DEPTNO) REFERENCES DEPARTMENT;


SELECT * FROM DEPARTMENT d ;
--학생
--이름 NN,아이디 UNIQUE,주민번호UNIQUE,FK DEPTNO,FK PROFNO
ALTER TABLE STUDENT MODIFY (NAME NOT NULL);
ALTER TABLE STUDENT MODIFY (USERID CONSTRAINT STUD_STUDNO_UK UNIQUE);--COLUNM LEVEL
ALTER TABLE STUDENT ADD CONSTRAINT STUD_IDNUM_UK UNIQUE(IDNUM);--TABLE LEVEL
ALTER TABLE STUDENT MODIFY (DEPTNO REFERENCES DEPARTMENT);
ALTER TABLE STUDENT ADD FOREIGN KEY (PROFNO) REFERENCES PROFESSOR;

SELECT * FROM STUDENT ;
SELECT * FROM PROFESSOR;







