SELECT *FROM PROFESSOR p;
ALTER TABLE DEPARTMENT MODIFY (DEPTNO CONSTRAINT DEPARTMENT_PK PRIMARY KEY);
SELECT STUDNO,NAME,ROWID,ROWNUM FROM STUDENT;

--DEPARTMENT 테이블 DMANE에 고유 인덱스 생성
CREATE INDEX IDX_DEPT_NAME ON DEPARTMENT(DNAME);

DROP INDEX IDX_STUD_DEPTNO_GRAED;

SELECT/*+ INDEX_DECE(DEPARTMENT DEPARTMENT_PK)  */ * FROM DEPARTMENT;

--STUDENT BIRTHDAY에 비고유 인덱스 생성
CREATE INDEX IDX_STUD_BIRTHDATE ON STUDENT(BIRTHDATE);

--STUDENT테이블의 DEPTNO,GRAED에 결합 인덱스 생성
CREATE INDEX IDX_STUD_DEPTNO_GRAED ON STUDENT(DEPTNO, GRAED DESC);

--VIEW 오타내기
--SELECT DISTINCT GRAED,DEPTNO FROM STUDENT S;

SELECT * FROM STUDENT;

--VIEW 생성
CREATE OR REPLACE VIEW VIEW_STUD AS
SELECT STUDNO,NAME,USERID,DEPTNO FROM STUDENT;

SELECT DEPTNO,COUNT(*)
FROM VIEW_STUD
WHERE DEPTNO <>201
GROUP BY DEPTNO;

INSERT INTO VIEW_STUD VALUES (12345,'홍길동',NULL); 

SELECT *FROM  VIEW_STUD;
SELECT *FROM (SELECT STUDNO,NAME,DEPTNO FROM STUDENT);

SELECT *FROM  STUDENT;

CREATE FORCE VIEW VIEW_STUD2 AS--FORCE는 오타난 테이블 생성
SELECT *FROM  STUDEN;

--학번,이름,학과번호,학과이름으로 VIEW_STUD_DEPT라는 뷰를 생성
CREATE VIEW VIEW_STUD_DEPT AS
SELECT STUDNO,NAME,DEPTNO,DNAME
FROM STUDENT s NATURAL JOIN DEPARTMENT d ;

SELECT *FROM VIEW_STUD_DEPT;

-- 11111,고길동,101,컴퓨터공학과 이거는 추가 불가
INSERT INTO VIEW_STUD_DEPT VALUES(11111,'고길동',101,'컴퓨터공학과');

--학과별 인원수를 조회하여 VIEW_STUD_DEPT2 라는 이름의 VIEW 생성
CREATE VIEW VIEW_STUD_DEPT2(DNO,CNT) AS
SELECT DEPTNO,COUNT(*)
FROM STUDENT
GROUP BY DEPTNO
ORDER BY 1;

SELECT *FROM VIEW_STUD_DEPT2;

--인라인 뷰
SELECT * FROM BOARD;
DROP  SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD;

--ALTER SEQUENCE SEQ_BOARD START WITH 1;

INSERT INTO BOARD(NO,TITLE,CONTENT,WRITER) 
	VALUES(SEQ_BOARD.NEXTVAL,'제목'|| SEQ_BOARD.CURRVAL,'내용','작성자');--한개씩 추가
	
INSERT INTO BOARD(NO,TITLE,CONTENT,WRITER) 
	SELECT SEQ_BOARD.NEXTVAL,TITLE,CONTENT,WRITER FROM BOARD;--여러개 추가

	SELECT * FROM BOARD

-- 한페이지에 몇개씩?
SELECT*FROM(	
SELECT ROWNUM RN, A. *
FROM(
	SELECT B.* FROM BOARD B
	--WHERE ROWNUM <= 10
	ORDER BY 1 DESC
	)A
)
WHERE ROWNUM <= 30 AND RN > (4-1)*30;


SELECT *FROM (
	SELECT /*+ INDEX_DESC(B SYS_C007005)*/ B.*,ROWNUM RN 
	FROM BOARD B
	WHERE NO > 0
)A;

WITH A AS(
	SELECT /*+ INDEX_DESC(B SYS_C007005)*/ B.*,ROWNUM RN 
	FROM BOARD B
	WHERE NO > 0
)
SELECT *
FROM A
WHERE ROWNUM <=10
AND RN > 10;

--FILE SYSTEM
--FILE의 권한

SELECT *FROM HR.EMPLOYEES;

SELECT D.* FROM STUDENT D;
SELECT SYSDATE FROM DUAL;

SELECT *FROM SYS.DUAL;

SELECT * FROM HR.EMPLOYEES;
SELECT * FROM EMP;



CREATE SYNONYM EMP FOR HR.EMPLOYEES;

CREATE PUBLIC SYNONYM STU FOR SAMPLE.STUDENT;

SELECT * FROM STU;



--사전
--접두어 : USER_ALL_DBA_
SELECT * FROM USER_TABLES;

SELECT * FROM ALL_TABLES WHERE OWNER = 'SAMPLE';

SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME='BOARD';--BOARD라는 테이블 이름만 출력 확인

SELECT * FROM USER_CONSTRAINTS; --제약 조건 넣기

SELECT * FROM USER_INDEXES; --인덱스 확인

SELECT * FROM STUDENT s ;

